# Generated by Django 5.1.4 on 2025-01-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_status_is_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status_is_banner',
            new_name='is_banner',
        ),
    ]
