# Generated by Django 5.1.4 on 2025-01-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_status_is_banner_product_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
