# Generated by Django 5.1.4 on 2024-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=18, unique=True)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('profile_image', models.CharField(max_length=200)),
            ],
        ),
    ]
