# Generated by Django 5.1.4 on 2024-12-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
