# Generated by Django 5.1.4 on 2024-12-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_forgetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
