# Generated by Django 5.1.4 on 2024-12-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_forgetpassword_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgetpassword',
            old_name='time',
            new_name='time_created',
        ),
    ]
